export const CURRENCY_TO_COINGECKO: Record<string, string> = {
  USDT: "tether",
  USDC: "usd-coin",
  GMT: "gmt-token",
  BTC: "bitcoin",
  ETH: "ethereum",
  BNB: "binancecoin",
  SOL: "solana",
  TON: "the-open-network",
};

export const WALLET_TO_CURRENCY: Record<string, string> = {
  VIRTUAL_GMT: "GMT",
  VIRTUAL_BTC: "BTC",
  VIRTUAL_ETH: "ETH",
  VIRTUAL_BNB: "BNB",
  VIRTUAL_SOL: "SOL",
  VIRTUAL_TON: "TON",
  VIRTUAL_USDC: "USDC",
  VIRTUAL_USDT: "USDT",
};

export const FIAT_OPTIONS: Array<{ currency: string; label: string }> = [
  { currency: "AED", label: "UAE Dirham" },
  { currency: "ALL", label: "Albanian Lek" },
  { currency: "AMD", label: "Armenian Dram" },
  { currency: "ANG", label: "Netherlands Antillean Guilder" },
  { currency: "AOA", label: "Angolan Kwanza" },
  { currency: "ARS", label: "Argentine Peso" },
  { currency: "AUD", label: "Australian Dollar" },
  { currency: "AWG", label: "Aruban Florin" },
  { currency: "AZN", label: "Azerbaijani Manat" },
  { currency: "BAM", label: "Bosnian Mark" },
  { currency: "BBD", label: "Barbadian Dollar" },
  { currency: "BDT", label: "Bangladeshi Taka" },
  { currency: "BGN", label: "Bulgarian Lev" },
  { currency: "BHD", label: "Bahraini Dinar" },
  { currency: "BMD", label: "Bermudian Dollar" },
  { currency: "BND", label: "Brunei Dollar" },
  { currency: "BOB", label: "Bolivian Boliviano" },
  { currency: "BRL", label: "Brazilian Real" },
  { currency: "BSD", label: "Bahamian Dollar" },
  { currency: "BTN", label: "Bhutanese Ngultrum" },
  { currency: "BWP", label: "Botswana Pula" },
  { currency: "BYN", label: "Belarusian Ruble" },
  { currency: "BZD", label: "Belize Dollar" },
  { currency: "CAD", label: "Canadian Dollar" },
  { currency: "CHF", label: "Swiss Franc" },
  { currency: "CLP", label: "Chilean Peso" },
  { currency: "CNY", label: "Chinese Yuan" },
  { currency: "COP", label: "Colombian Peso" },
  { currency: "CRC", label: "Costa Rican Colón" },
  { currency: "CVE", label: "Cape Verdean Escudo" },
  { currency: "CZK", label: "Czech Koruna" },
  { currency: "DJF", label: "Djiboutian Franc" },
  { currency: "DKK", label: "Danish Krone" },
  { currency: "DOP", label: "Dominican Peso" },
  { currency: "DZD", label: "Algerian Dinar" },
  { currency: "EGP", label: "Egyptian Pound" },
  { currency: "ERN", label: "Eritrean Nakfa" },
  { currency: "ETB", label: "Ethiopian Birr" },
  { currency: "EUR", label: "Euro" },
  { currency: "FJD", label: "Fijian Dollar" },
  { currency: "GBP", label: "British Pound" },
  { currency: "GEL", label: "Georgian Lari" },
  { currency: "GHS", label: "Ghanaian Cedi" },
  { currency: "GIP", label: "Gibraltar Pound" },
  { currency: "GMD", label: "Gambian Dalasi" },
  { currency: "GTQ", label: "Guatemalan Quetzal" },
  { currency: "GYD", label: "Guyanese Dollar" },
  { currency: "HKD", label: "Hong Kong Dollar" },
  { currency: "HNL", label: "Honduran Lempira" },
  { currency: "HTG", label: "Haitian Gourde" },
  { currency: "HUF", label: "Hungarian Forint" },
  { currency: "IDR", label: "Indonesian Rupiah" },
  { currency: "ILS", label: "Israeli New Shekel" },
  { currency: "INR", label: "Indian Rupee" },
  { currency: "ISK", label: "Icelandic Króna" },
  { currency: "JMD", label: "Jamaican Dollar" },
  { currency: "JOD", label: "Jordanian Dinar" },
  { currency: "JPY", label: "Japanese Yen" },
  { currency: "KES", label: "Kenyan Shilling" },
  { currency: "KGS", label: "Kyrgyzstani Som" },
  { currency: "KHR", label: "Cambodian Riel" },
  { currency: "KMF", label: "Comorian Franc" },
  { currency: "KRW", label: "South Korean Won" },
  { currency: "KWD", label: "Kuwaiti Dinar" },
  { currency: "KYD", label: "Cayman Islands Dollar" },
  { currency: "KZT", label: "Kazakhstani Tenge" },
  { currency: "LAK", label: "Lao Kip" },
  { currency: "LKR", label: "Sri Lankan Rupee" },
  { currency: "LRD", label: "Liberian Dollar" },
  { currency: "LSL", label: "Lesotho Loti" },
  { currency: "MAD", label: "Moroccan Dirham" },
  { currency: "MDL", label: "Moldovan Leu" },
  { currency: "MGA", label: "Malagasy Ariary" },
  { currency: "MKD", label: "Macedonian Denar" },
  { currency: "MNT", label: "Mongolian Tögrög" },
  { currency: "MOP", label: "Macanese Pataca" },
  { currency: "MRU", label: "Mauritanian Ouguiya" },
  { currency: "MUR", label: "Mauritian Rupee" },
  { currency: "MVR", label: "Maldivian Rufiyaa" },
  { currency: "MWK", label: "Malawian Kwacha" },
  { currency: "MXN", label: "Mexican Peso" },
  { currency: "MYR", label: "Malaysian Ringgit" },
  { currency: "MZN", label: "Mozambican Metical" },
  { currency: "NAD", label: "Namibian Dollar" },
  { currency: "NGN", label: "Nigerian Naira" },
  { currency: "NOK", label: "Norwegian Krone" },
  { currency: "NPR", label: "Nepalese Rupee" },
  { currency: "NZD", label: "New Zealand Dollar" },
  { currency: "OMR", label: "Omani Rial" },
  { currency: "PEN", label: "Peruvian Sol" },
  { currency: "PGK", label: "Papua New Guinean Kina" },
  { currency: "PHP", label: "Philippine Peso" },
  { currency: "PKR", label: "Pakistani Rupee" },
  { currency: "PLN", label: "Polish Złoty" },
  { currency: "PYG", label: "Paraguayan Guaraní" },
  { currency: "QAR", label: "Qatari Riyal" },
  { currency: "RON", label: "Romanian Leu" },
  { currency: "RSD", label: "Serbian Dinar" },
  { currency: "RUB", label: "Russian Ruble" },
  { currency: "RWF", label: "Rwandan Franc" },
  { currency: "SAR", label: "Saudi Riyal" },
  { currency: "SBD", label: "Solomon Islands Dollar" },
  { currency: "SCR", label: "Seychellois Rupee" },
  { currency: "SEK", label: "Swedish Krona" },
  { currency: "SLE", label: "Sierra Leonean Leone" },
  { currency: "SRD", label: "Surinamese Dollar" },
  { currency: "STN", label: "São Tomé Dobra" },
  { currency: "SZL", label: "Swazi Lilangeni" },
  { currency: "THB", label: "Thai Baht" },
  { currency: "TJS", label: "Tajikistani Somoni" },
  { currency: "TMT", label: "Turkmenistani Manat" },
  { currency: "TND", label: "Tunisian Dinar" },
  { currency: "TOP", label: "Tongan Paʻanga" },
  { currency: "TTD", label: "Trinidad & Tobago Dollar" },
  { currency: "TWD", label: "New Taiwan Dollar" },
  { currency: "TZS", label: "Tanzanian Shilling" },
  { currency: "UAH", label: "Ukrainian Hryvnia" },
  { currency: "UGX", label: "Ugandan Shilling" },
  { currency: "UYU", label: "Uruguayan Peso" },
  { currency: "UZS", label: "Uzbekistani Som" },
  { currency: "VND", label: "Vietnamese Dong" },
  { currency: "VUV", label: "Vanuatu Vatu" },
  { currency: "WST", label: "Samoan Tālā" },
  { currency: "XAF", label: "Central African CFA Franc" },
  { currency: "XCD", label: "East Caribbean Dollar" },
  { currency: "XOF", label: "West African CFA Franc" },
  { currency: "XPF", label: "CFP Franc" },
  { currency: "ZAR", label: "South African Rand" },
  { currency: "ZMW", label: "Zambian Kwacha" },
];
